version: '3'

services:
  devon_mysql:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    restart: unless-stopped
    expose:
      - 3307
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./devon-api/:/var/www/devon-api/
    links:
      - devon_mysql:devon
    depends_on:
      - devon_mysql
    networks:
      - symfony

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./devon-api/:/var/www/devon-api/
    ports:
      - 8088:80
    networks:
      - symfony
    depends_on:
      - php
  angular-ui:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    ports:
      - "4201:4201"
    volumes:
      - ./devon:/var/www/devon/
      - /devon/node_modules
    networks:
      - symfony

networks:
  symfony: