#index:
#    path: /
#    controller: App\Controller\DefaultController::index



server_upload_list:
  path: /v1/servers/upload_list
  controller: App\Controller\ServersController::listFromFile
  methods: POST

server_list:
  path: /v1/servers/list
  controller: App\Controller\ServersController::list
  methods: GET
  defaults:
    page: 1
    requirements:
      page: '\d+'

server_upload:
  path: /v1/servers/upload
  controller: App\Controller\ServersController::upload
  methods: POST

